import React from 'react';
import ReactECharts from 'echarts-for-react';

export const InvestigationGraph: React.FC = () => {
  // Mock data for the investigation relation graph
  const graphData = [
    { name: 'INC-994201', category: 0, symbolSize: 50, value: 'ITSM Incident' },
    { name: 'jdoe', category: 1, symbolSize: 40, value: 'User' },
    { name: 'DESKTOP-JDOE', category: 2, symbolSize: 40, value: 'Laptop' },
    { name: 'jdoe@corp.local', category: 3, symbolSize: 35, value: 'AD Account' },
    { name: 'VPN Gateway', category: 4, symbolSize: 45, value: 'VPN' },
    { name: 'PA-5220-Edge', category: 5, symbolSize: 45, value: 'Firewall' },
    { name: 'SOC-Alert-883', category: 6, symbolSize: 50, value: 'SOC Alert' },
    { name: 'PB-Isolate-Endpoint', category: 7, symbolSize: 45, value: 'Playbook' }
  ];

  const graphLinks = [
    { source: 'INC-994201', target: 'SOC-Alert-883', label: { show: true, formatter: 'Generated By' } },
    { source: 'SOC-Alert-883', target: 'DESKTOP-JDOE', label: { show: true, formatter: 'Targets' } },
    { source: 'jdoe', target: 'jdoe@corp.local', label: { show: true, formatter: 'Owns' } },
    { source: 'jdoe', target: 'DESKTOP-JDOE', label: { show: true, formatter: 'Assigned To' } },
    { source: 'jdoe@corp.local', target: 'VPN Gateway', label: { show: true, formatter: 'Authenticates' } },
    { source: 'VPN Gateway', target: 'PA-5220-Edge', label: { show: true, formatter: 'Traverses' } },
    { source: 'DESKTOP-JDOE', target: 'PA-5220-Edge', label: { show: true, formatter: 'Network Route' } },
    { source: 'SOC-Alert-883', target: 'PB-Isolate-Endpoint', label: { show: true, formatter: 'Triggers' } },
    { source: 'PB-Isolate-Endpoint', target: 'DESKTOP-JDOE', label: { show: true, formatter: 'Acts On' } }
  ];

  const categories = [
    { name: 'Incident', itemStyle: { color: '#ec4899' } },
    { name: 'User', itemStyle: { color: '#10b981' } },
    { name: 'Device', itemStyle: { color: '#64748b' } },
    { name: 'Identity', itemStyle: { color: '#eab308' } },
    { name: 'Network', itemStyle: { color: '#0ea5e9' } },
    { name: 'Security', itemStyle: { color: '#ef4444' } },
    { name: 'Alert', itemStyle: { color: '#f97316' } },
    { name: 'Automation', itemStyle: { color: '#8b5cf6' } }
  ];

  const option = {
    backgroundColor: '#0b1120',
    title: {
      text: 'Investigation Relation Graph',
      subtext: 'Entity mapping for INC-994201',
      top: 'top',
      left: 'left',
      textStyle: {
        color: '#f8fafc',
        fontSize: 20,
        fontFamily: 'Inter, sans-serif'
      },
      subtextStyle: {
        color: '#94a3b8'
      }
    },
    tooltip: {
      formatter: function (params: any) {
        if (params.dataType === 'node') {
          return `<div style="padding: 4px;">
            <strong style="color: ${params.color}; font-size: 14px;">${params.data.name}</strong><br/>
            <span style="color: #cbd5e1; font-size: 12px;">Type: ${params.data.value}</span>
          </div>`;
        } else if (params.dataType === 'edge') {
          return `${params.data.source} > <strong>${params.data.label?.formatter || 'Connects to'}</strong> > ${params.data.target}`;
        }
      },
      backgroundColor: 'rgba(30, 41, 59, 0.9)',
      borderColor: '#334155',
      textStyle: {
        color: '#f8fafc'
      }
    },
    legend: [{
      data: categories.map(a => a.name),
      textStyle: {
        color: '#cbd5e1'
      },
      bottom: 20
    }],
    animationDuration: 1500,
    animationEasingUpdate: 'quinticInOut',
    series: [
      {
        name: 'Investigation Graph',
        type: 'graph',
        layout: 'force',
        data: graphData,
        links: graphLinks,
        categories: categories,
        roam: true,
        label: {
          show: true,
          position: 'right',
          formatter: '{b}',
          color: '#e2e8f0'
        },
        force: {
          repulsion: 1000,
          edgeLength: [100, 200],
          gravity: 0.1
        },
        lineStyle: {
          color: 'source',
          curveness: 0.2,
          opacity: 0.7,
          width: 2
        },
        edgeSymbol: ['none', 'arrow'],
        edgeSymbolSize: [4, 10],
        edgeLabel: {
          fontSize: 11,
          color: '#94a3b8'
        },
        emphasis: {
          focus: 'adjacency',
          lineStyle: {
            width: 4
          }
        }
      }
    ]
  };

  return (
    <div style={{
      padding: '2.5rem',
      backgroundColor: '#0b1120',
      borderRadius: '1rem',
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.5)',
      border: '1px solid #1e293b',
      maxWidth: '1000px',
      margin: '0 auto'
    }}>
      <ReactECharts
        option={option}
        style={{ height: '600px', width: '100%' }}
        theme="dark"
      />
    </div>
  );
};
